# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A2a < Formula
  desc "The official command-line interface for A2A (Agent-to-Agent) compatible agents."
  homepage "https://github.com/a2aproject/a2a-cli"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/a2aproject/a2a-cli/releases/download/v0.2.0/a2a_0.2.0_darwin_amd64.tar.gz"
      sha256 "9ee353376f10a27c443e3ff0718d20277a0125e360b37077c269faa7151bcccf"

      define_method(:install) do
        bin.install "a2a"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/a2aproject/a2a-cli/releases/download/v0.2.0/a2a_0.2.0_darwin_arm64.tar.gz"
      sha256 "3c6707a95498678ac23f938f5f7495e23de6d381d098577860ffba2da64de357"

      define_method(:install) do
        bin.install "a2a"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/a2aproject/a2a-cli/releases/download/v0.2.0/a2a_0.2.0_linux_amd64.tar.gz"
      sha256 "78ab1a096ad76d631f41018eae7dec00a59fdbf121bb917c7b65623f09f83988"
      define_method(:install) do
        bin.install "a2a"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/a2aproject/a2a-cli/releases/download/v0.2.0/a2a_0.2.0_linux_arm64.tar.gz"
      sha256 "1b1dcc44704de56af070c7028014c43d7b03db924abb6e18a8e5dbc66124ec64"
      define_method(:install) do
        bin.install "a2a"
      end
    end
  end

  test do
    system "#{bin}/a2a", "version"
  end
end
