# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A2a < Formula
  desc "The official command-line interface for A2A (Agent-to-Agent) compatible agents."
  homepage "https://github.com/a2aproject/a2a-cli"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/a2aproject/a2a-cli/releases/download/v0.3.0/a2a_0.3.0_darwin_amd64.tar.gz"
      sha256 "0d70db7592d1ed55989a3ee6a64f8325145f95d431d3e885ff86a0717ae20126"

      define_method(:install) do
        bin.install "a2a"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/a2aproject/a2a-cli/releases/download/v0.3.0/a2a_0.3.0_darwin_arm64.tar.gz"
      sha256 "812f199cb1dbd29949c34d74c7a716394a10606ac62f342f86ba07e67b46936a"

      define_method(:install) do
        bin.install "a2a"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/a2aproject/a2a-cli/releases/download/v0.3.0/a2a_0.3.0_linux_amd64.tar.gz"
      sha256 "faccdeac8ca30c6727cfd626681f6b38b7833c417aac45c6092a73ed8c481037"
      define_method(:install) do
        bin.install "a2a"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/a2aproject/a2a-cli/releases/download/v0.3.0/a2a_0.3.0_linux_arm64.tar.gz"
      sha256 "6c93900fdb91ad061846447d9bd6981a7aa0b0ab0d506c8a4243b0f25b070112"
      define_method(:install) do
        bin.install "a2a"
      end
    end
  end

  test do
    system "#{bin}/a2a", "version"
  end
end
